### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by rnowling** [nowling-lab/TanoaPeakSimulator#2]
I ran Tanoa from the dev branch as follows:

```
$ tanoa_call_peaks --depth-file /archive1/rnowling/enhancer-localization-precision/drosophila-starr-seq-arnold/data/filtered_alignments/dmel/cDNA_Dmel_rep2.depth --outputdir starr_peaks
```

and it crashed with the following error:

```
(venv) rnowling@parker:~/Projects/TanoaPeakSimulator$ tanoa_call_peaks --depth-file /archive1/rnowling/enhancer-localization-precision/drosophila-starr-seq-arnold/data/filtered_alignments/dmel/cDNA_Dmel_rep2.depth --outputdir starr_peaks
Reading in  chr2L
Compressing chr2L
Calling peaks
Cleaning peaks
Traceback (most recent call last):
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/bin/tanoa_call_peaks", line 4, in <module>
    __import__('pkg_resources').run_script('Tanoa==0.1', 'tanoa_call_peaks')
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/Tanoa-0.1-py3.7.egg/EGG-INFO/scripts/tanoa_call_peaks", line 44, in <module>
    do_call_peaks(args)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/Tanoa-0.1-py3.7.egg/EGG-INFO/scripts/tanoa_call_peaks", line 17, in do_call_peaks
    read_and_call(args.depth_file, args.outputdir, args.write_depths)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/Tanoa-0.1-py3.7.egg/caller/__init__.py", line 34, in read_and_call
    prossess_and_write_peaks(chromosome, compressed_depths, output_file, write_depths, compressed_depths_output)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/Tanoa-0.1-py3.7.egg/caller/__init__.py", line 64, in prossess_and_write_peaks
    peak_list = clean_peaks(peak_list, compressed_depths)
  File "/home/rnowling/Projects/TanoaPeakSimulator/venv/lib/python3.7/site-packages/Tanoa-0.1-py3.7.egg/caller/__init__.py", line 210, in clean_peaks
    if peak not in peak_black_dict:
NameError: name 'peak_black_dict' is not defined
```

**Comment by FriendlyBandit** [comment]
Yea, I ended up working on the wrong branch last week and when I thought I
fixed it, it broke things on dev. I was able to fix it on my local dev
brach, I just haven't pushed yet.

 John
